# Generated by Django 3.1.3 on 2021-03-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210327_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='links',
            new_name='likes',
        ),
    ]
